# Generated by Django 4.2.26 on 2025-12-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("instructor", "Instructor"),
                    ("pharmacist", "Pharmacist"),
                    ("admin", "Admin"),
                ],
                default="student",
                help_text="User role determines access permissions",
                max_length=20,
            ),
        ),
    ]
