# Generated by Django 5.0.14 on 2025-12-10 09:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of correct answers",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_questions",
                    models.IntegerField(
                        help_text="Total number of questions in the exam",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        help_text="Current status of the exam attempt",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        help_text="The student taking the exam",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_answer",
                    models.CharField(
                        choices=[
                            ("A", "Option A"),
                            ("B", "Option B"),
                            ("C", "Option C"),
                            ("D", "Option D"),
                        ],
                        help_text="The answer option selected by the student",
                        max_length=1,
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        help_text="Whether the selected answer is correct"
                    ),
                ),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        help_text="The exam attempt this answer belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_answers",
                        to="exams.examattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["answered_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="The question text")),
                (
                    "option_a",
                    models.CharField(help_text="Option A text", max_length=500),
                ),
                (
                    "option_b",
                    models.CharField(help_text="Option B text", max_length=500),
                ),
                (
                    "option_c",
                    models.CharField(help_text="Option C text", max_length=500),
                ),
                (
                    "option_d",
                    models.CharField(help_text="Option D text", max_length=500),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[
                            ("A", "Option A"),
                            ("B", "Option B"),
                            ("C", "Option C"),
                            ("D", "Option D"),
                        ],
                        help_text="The correct answer option",
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Question category (e.g., Pharmacology, Clinical Pharmacy)",
                        max_length=100,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        help_text="Question difficulty level",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "difficulty", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="exams_quest_categor_661fca_idx"
                    ),
                    models.Index(
                        fields=["difficulty"], name="exams_quest_difficu_7bcf5f_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="examattempt",
            name="questions",
            field=models.ManyToManyField(
                help_text="Questions included in this exam attempt",
                through="exams.ExamAnswer",
                to="exams.question",
            ),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="question",
            field=models.ForeignKey(
                help_text="The question being answered",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_answers",
                to="exams.question",
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["student", "-started_at"], name="exams_exama_student_b4c984_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["status"], name="exams_exama_status_6897fc_idx"),
        ),
        migrations.AddIndex(
            model_name="examanswer",
            index=models.Index(
                fields=["attempt", "question"], name="exams_exama_attempt_944fe7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examanswer",
            index=models.Index(
                fields=["is_correct"], name="exams_exama_is_corr_97ff45_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examanswer",
            unique_together={("attempt", "question")},
        ),
    ]
