# Generated by Django 5.0.14 on 2025-12-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examanswer",
            name="is_correct",
            field=models.BooleanField(
                default=False, help_text="Whether the selected answer is correct"
            ),
        ),
    ]
