# Generated by Django 5.0.14 on 2025-12-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_alter_examanswer_is_correct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examanswer",
            name="selected_answer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Option A"),
                    ("B", "Option B"),
                    ("C", "Option C"),
                    ("D", "Option D"),
                ],
                help_text="The answer option selected by the student",
                max_length=1,
                null=True,
            ),
        ),
    ]
