# Generated by Django 4.2.26 on 2025-12-12 08:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Course title", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Detailed course description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Course price",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (USD, NGN, etc.)",
                        max_length=3,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the course is published and visible to students",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the course was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the course was last updated"
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        help_text="Instructor who created this course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "hub3660_courses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Session title", max_length=200)),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        help_text="When the session is scheduled to start"
                    ),
                ),
                (
                    "zoom_meeting_id",
                    models.CharField(
                        blank=True,
                        help_text="Zoom meeting ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "zoom_join_url",
                    models.URLField(
                        blank=True, help_text="Zoom meeting join URL", null=True
                    ),
                ),
                (
                    "recording_url",
                    models.URLField(
                        blank=True, help_text="URL to session recording", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the session was created"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this session belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="hub3660.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "db_table": "hub3660_sessions",
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["course"], name="hub3660_ses_course__3528d5_idx"
                    ),
                    models.Index(
                        fields=["scheduled_at"], name="hub3660_ses_schedul_d6d9ec_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Payment status for this enrollment",
                        max_length=20,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment provider transaction ID",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the enrollment was created"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course the student is enrolled in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="hub3660.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student enrolled in the course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "db_table": "hub3660_enrollments",
                "ordering": ["-enrolled_at"],
                "indexes": [
                    models.Index(
                        fields=["student"], name="hub3660_enr_student_43abb9_idx"
                    ),
                    models.Index(
                        fields=["course"], name="hub3660_enr_course__e5c1c9_idx"
                    ),
                    models.Index(
                        fields=["payment_status"], name="hub3660_enr_payment_2f0626_idx"
                    ),
                    models.Index(
                        fields=["enrolled_at"], name="hub3660_enr_enrolle_67af38_idx"
                    ),
                ],
                "unique_together": {("student", "course")},
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["instructor"], name="hub3660_cou_instruc_efc75a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_published"], name="hub3660_cou_is_publ_017bb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["created_at"], name="hub3660_cou_created_9985b4_idx"
            ),
        ),
    ]
