# Generated by Django 4.2.26 on 2025-12-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub3660", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="s3_recording_key",
            field=models.CharField(
                blank=True,
                help_text="S3 object key for the session recording",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="recording_url",
            field=models.URLField(
                blank=True,
                help_text="URL to session recording (deprecated - use s3_recording_key)",
                null=True,
            ),
        ),
    ]
